export const REACT_APP_DASHBOARD_URL = process.env.REACT_APP_DASHBOARD_URL;
export const REACT_APP_DASHBOARD_SERVICE_URL = process.env.REACT_APP_DASHBOARD_SERVICE_URL;
export const REACT_APP_ORGANIZATION_ID =  process.env.REACT_APP_ORGANIZATION_ID;
