# name: Deploy to S3

# on:
#   push:
#     branches: [dev]

# jobs:
#   build_and_deploy_to_dev:
#     runs-on: ubuntu-latest
#     name: Run npm install and build

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm install and build
#         run: |
#           npm clean-install
#           npm run --silent build --if-present

#       - name: Deploy build to AWS s3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --follow-symlinks --delete --exclude '.git/*'
#         env:
#           AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           REACT_APP_DASHBOARD_URL: ${{ secrets.REACT_APP_DASHBOARD_URL }}
#           REACT_APP_DASHBOARD_SERVICE_URL: ${{ secrets.REACT_APP_DASHBOARD_SERVICE_URL }}
#           REACT_APP_ORGANIZATION_ID: ${{ secrets.REACT_APP_ORGANIZATION_ID }}
#           SOURCE_DIR: "./build/" # optional: defaults to entire repository
